var automationframework = connect('localhost:27017/automationframework');
//test comment
var BrowserVarID = ObjectId();
var ClickID = ObjectId();
var OpenBrowserID = ObjectId();
var SendKeysID = ObjectId();
var VerifyTextID = ObjectId();
var SearchAmazonID = ObjectId();
var SelectItemID = ObjectId();
var AddToCartID = ObjectId();
var VerifyItemAddedToCartID = ObjectId();
var AddStarTreckID = ObjectId();
var AmazonShoppingTSID = ObjectId();
var AmazonShoppingEXID = ObjectId();

//selenium based actions
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361857038191-12505-27095"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361857045292-1778-6378"}],"name":"Click on Element","description":"Click on element","type":"script","status":"Automated","_id":ClickID,"collection":[],"script":"actions.selenium.Click.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"URL","possiblevalues":[],"parametertype":"String","id":"1361857291996-19836-917"},{"name":"Browser Type","possiblevalues":["Internet Explorer","Firefox","Chrome"],"parametertype":"String","id":"1361857319350-22783-32022"}],"name":"Open Browser","description":"","type":"script","status":"Automated","_id":OpenBrowserID,"collection":[],"script":"actions.selenium.Browser.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361859197536-31667-17007"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361859201529-30055-7133"},{"name":"Key","possiblevalues":[],"parametertype":"String","id":"1361859371895-8512-9755"},{"name":"Text","possiblevalues":[],"parametertype":"String","id":"1361859371895-8512-9793"}],"name":"Send Keys to Element","description":"Look up http://selenium.googlecode.com/git/docs/api/java/org/openqa/selenium/Keys.html for key names","type":"script","status":"Automated","_id":SendKeysID,"collection":[],"script":"actions.selenium.SendKeys.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"},{"name":"Text","possiblevalues":[],"parametertype":"String","id":"1361900791173-11855-8017"}],"name":"Verify Text in Element","description":"","type":"script","status":"Automated","_id":VerifyTextID,"collection":[],"script":"actions.selenium.VerifyText.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[],"name":"Close All Browsers","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.CloseBrowser.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[],"name":"Close Current Window","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.CloseWindow.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"Window Name","possiblevalues":["Default Window"],"parametertype":"String","id":"1361900718349-8440-28310"}],"name":"Switch to Browser Window","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.SwitchWindow.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"}],"name":"Submit Form","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.Submit.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"}],"name":"Right Click on Element","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.RightClick.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"}],"name":"Mouse Over Element","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.MouseOver.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"},{"name":"Number of Matches","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28333"}],"name":"Verify Element Exists","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.Exists.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"URL","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"}],"name":"Navigate to URL","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.NavigateToURL.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"},{"name":"Is Checked","possiblevalues":[],"parametertype":"Boolean","id":"1361900718349-8440-28333"}],"name":"Verify Checkbox","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.VerifyCheckBox.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"Cookie Name","possiblevalues":["ALL"],"parametertype":"String","id":"1361900718349-8440-28310"}],"name":"Delete Cookie","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.DeleteCookie.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"}],"name":"Double Click on Element","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.DoubleClick.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"Name","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"Index","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28312"}],"name":"Switch To Frame","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.SwitchToFrame.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[],"name":"Switch To Default Content","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.SwitchToDefaultContent.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"},{"name":"Is Enabled","possiblevalues":[],"parametertype":"Boolean","id":"1361900718349-8440-28333"},{"name":"Is Visible","possiblevalues":[],"parametertype":"Boolean","id":"1361900718349-9440-28344"},{"name":"Is Focused","possiblevalues":[],"parametertype":"Boolean","id":"1361900718349-9440-28888"}],"name":"Verify Element State","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.VerifyElementState.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"Code","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"}],"name":"Execute Javascript","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.ExecuteJavascript.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"}],"name":"Set Focus on Element","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.SetFocus.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"Name","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"}],"name":"Get Cookie Value","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.GetCookieValue.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"},{"name":"Attribute Name","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28311"},{"name":"Value","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28314"}],"name":"Verify Element Attribute","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.VerifyAttribute.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"},{"name":"Item Label","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28311"},{"name":"Item Value","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28314"}],"name":"Verify Selected List Item","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.VerifySelectedItem.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"Title","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"}],"name":"Verify Page Title","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.VerifyPageTitle.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"}],"name":"Get Element Text","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.GetText.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[],"name":"Refresh","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.Refresh.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[],"name":"Go Forward","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.GoForward.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[],"name":"Go Back","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.GoBack.run","project":projectName});
automationframework.actions.save({"tag":["general"],"params":[{"name":"Seconds","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"}],"name":"Wait","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.general.Wait.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"From ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"From ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"},{"name":"To ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28322"},{"name":"To ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16328"}],"name":"Drag And Drop to Element","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.DragAndDrop.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"Value","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"Regular Expression","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28319"}],"name":"Verify Current URL Value","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.VerifyURL.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"},{"name":"Check","possiblevalues":[],"parametertype":"Boolean","id":"1361900718349-8440-28319"}],"name":"Set Checkbox","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.SetCheckBox.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"Seconds","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"}],"name":"Set Timeout","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.SetTimeout.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"},{"name":"Timeout In Seconds","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28319"}],"name":"Wait for Element","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.WaitForElement.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"},{"name":"Text","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28319"}],"name":"Set Text to Element","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.SetText.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"},{"name":"Visible Text","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28322"},{"name":"Value","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28335"},{"name":"Index","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28337"}],"name":"Select Item In Element","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.SelectItem.run","project":projectName});


automationframework.actions.save({"tag":["amazon","search"],"params":[{"name":"search for","possiblevalues":[],"parametertype":"String","id":"1361901171879-59-24985"}],"name":"Search Amazon","description":"","type":"collection","status":"Automated","_id":SearchAmazonID,"collection":[{"order":"1","actionid":SendKeysID.str,"host":"Default","executionflow":"Record Error Stop Test Case","returnvalue":"","parameters":[{"paramname":"ID","paramid":"1361859197536-31667-17007","paramvalue":"twotabsearchtextbox"},{"paramname":"ID Type","paramid":"1361859201529-30055-7133","paramvalue":"ID"},{"paramname":"Text","paramid":"1361859371895-8512-9793","paramvalue":"${search for}"}]},{"order":"2","actionid":ClickID.str,"host":"Default","executionflow":"Record Error Stop Test Case","returnvalue":"","parameters":[{"paramname":"ID","paramid":"1361857038191-12505-27095","paramvalue":"nav-submit-input"},{"paramname":"ID Type","paramid":"1361857045292-1778-6378","paramvalue":"Class Name"}]}],"script":"","project":projectName});
automationframework.actions.save({"tag":["amazon"],"params":[{"name":"Item Index","possiblevalues":[],"parametertype":"String","id":"1361902537334-29436-6570"}],"name":"Select Item","description":"","type":"collection","status":"Automated","_id":SelectItemID,"collection":[{"order":"1","actionid":ClickID.str,"host":"Default","executionflow":"Record Error Stop Test Case","returnvalue":"","parameters":[{"paramname":"ID","paramid":"1361857038191-12505-27095","paramvalue":"//*[@id=\"result_${Item Index}\"]/h3/a"},{"paramname":"ID Type","paramid":"1361857045292-1778-6378","paramvalue":"XPath"}]}],"script":"","project":projectName});
automationframework.actions.save({"tag":["amazon","cart"],"params":[],"name":"Add to Cart","description":"","type":"collection","status":"Automated","_id":AddToCartID,"collection":[{"order":"1","actionid":ClickID.str,"host":"Default","executionflow":"Record Error Stop Test Case","returnvalue":"","parameters":[{"paramname":"ID","paramid":"1361857038191-12505-27095","paramvalue":"submit.add-to-cart"},{"paramname":"ID Type","paramid":"1361857045292-1778-6378","paramvalue":"Name"}]}],"script":"","project":projectName});
automationframework.actions.save({"tag":["amazon","cart"],"params":[],"name":"Verify Item Added to Cart","description":"","type":"collection","status":"Automated","_id":VerifyItemAddedToCartID,"collection":[{"order":"1","actionid":VerifyTextID.str,"host":"Default","executionflow":"Record Error Stop Test Case","returnvalue":"","parameters":[{"paramname":"ID","paramid":"1361900718349-8440-28310","paramvalue":"confirm-text"},{"paramname":"ID Type","paramid":"1361900724396-8476-16304","paramvalue":"ID"},{"paramname":"Text","paramid":"1361900791173-11855-8017","paramvalue":"1 item added to Cart"}]}],"script":"","project":projectName});

automationframework.testcases.save({"tag":["amazon"],"name":"Add Star Trek to Cart","description":"","status":"Automated","_id":AddStarTreckID,"collection":[{"order":"1","actionid":OpenBrowserID.str,"host":"Default","executionflow":"Record Error Stop Test Case","returnvalue":"","parameters":[{"paramname":"URL","paramid":"1361857291996-19836-917","paramvalue":"www.amazon.com"},{"paramname":"Browser Type","paramid":"1361857319350-22783-32022","paramvalue":"${Browser}"}]},{"order":"2","actionid":SearchAmazonID.str,"host":"Default","executionflow":"Record Error Stop Test Case","returnvalue":"","parameters":[{"paramname":"search for","paramid":"1361901171879-59-24985","paramvalue":"Star Trek Blu Ray"}]},{"order":"3","actionid":SelectItemID.str,"host":"Default","executionflow":"Record Error Stop Test Case","returnvalue":"","parameters":[{"paramname":"Item Index","paramid":"1361902537334-29436-6570","paramvalue":"0"}]},{"order":"4","actionid":AddToCartID.str,"host":"Default","executionflow":"Record Error Stop Test Case","returnvalue":"","parameters":[]},{"order":"5","actionid":VerifyItemAddedToCartID.str,"host":"Default","executionflow":"Record Error Stop Test Case","returnvalue":"","parameters":[]}],"script":"","host":"","type":"collection","project":projectName});

automationframework.testsets.save({"name":"Amazon Shopping","testcases":[{"_id":AddStarTreckID.str}],"_id":AmazonShoppingTSID,"project":projectName});

automationframework.executions.save({"name":"Amazon Shopping","status":"Ready To Run","ignoreStatus":false,"testset":AmazonShoppingTSID.str,"resultID":"","baseStateTCID":"","testsetname":"Amazon Shopping","tag":[],"variables":[{"name":"Browser","value":"Firefox","tag":[""],"possibleValues":["Internet Explorer","Firefox","Chrome"],"_id":BrowserVarID.str}],"machines":[{"host":"dmitri-pc","vncport":"3006","port":"5009","tag":["qualification","aga","sadfasdf"],"state":"","baseState":"","resultID":"","baseStateTCID":"1370382670808-29606-27201","result":"","description":"host name is:Dmitri-PC","roles":["Default"],"_id":"5116ada4a5c8d4f00d000002"},{"host":"192.168.220.128","vncport":"3006","port":"5009","tag":[""],"state":"","baseState":"","resultID":"","baseStateTCID":"1370382670808-3320-9747","result":"","description":"host name is:SilkDevSQLVS2","roles":["Default"],"_id":"5117db04898578bc2f000001"},{"host":"192.168.8.1","vncport":"3006","port":"5009","tag":"","state":"","baseState":"","resultID":"","baseStateTCID":"1370382670808-10943-29261","result":"","description":"host name is:Dmitri-PC","roles":["Default"],"_id":"514798379c05dd140f000002"}],"_id":AmazonShoppingEXID.str,"project":projectName});

automationframework.variables.save({"tag":[""],"name":"Browser","value":"<NULL>","taskVar":true,"possibleValues":["Internet Explorer","Firefox","Chrome"],"project":projectName,"_id":BrowserVarID});


automationframework.actionTags.save({"value":"selenium","project":projectName,"_id":ObjectId()});
automationframework.actionTags.save({"value":"general","project":projectName,"_id":ObjectId()});
automationframework.actionTags.save({"value":"amazon","project":projectName,"_id":ObjectId()});
automationframework.actionTags.save({"value":"search","project":projectName,"_id":ObjectId()});
automationframework.actionTags.save({"value":"cart","project":projectName,"_id":ObjectId()});

automationframework.testcaseTags.save({"value":"amazon","project":projectName,"_id":ObjectId()});

automationframework.executiontestcases.save({"name":"Add Star Trek to Cart","tag":["amazon"],"status":"Not Run","host":"","vncport":"","resultID":"","result":"","startdate":null,"enddate":null,"runtime":"","error":"","_id":ObjectId().str,"testcaseID":AddStarTreckID,"executionID":AmazonShoppingEXID.str,"project":projectName});